# Generated by Django 6.0 on 2026-03-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
